---
title: "Création de DataLilou"
author: "Lilou Kieffer"
date: "2023-05-10"
output: html_document
---

#Chargement DataGuyafor_VOLUMES
```{r}
#on charge la base de données sur laquelles on va pouvoir appliquer les derniers filtrages afin d'obtenir DataLilou
load(here("Datas", "DataGuyafor_VOLUMES.RData"))
#affocher DataGuyafor_VOLUMES_RESULT
View(DataGuyafor_VOLUMES)
```

#Chargement "Classi_Ess_Com_finale" pour créer la colonne "Ess_Com"
```{r}
#on charge le tableau Excel comportant les 255 essences classées comme commerciales afin de les faire matcher avec celles présentes dans la base

library(readxl)
Classi_Ess_Com_Finale <- read_excel("Classi_Ess_Com_Finale.xlsx")
View(Classi_Ess_Com_Finale)
```

#Chargement 'Points_Finaux" pour avoir les Idtree qui nous intéressent 
```{r}
#on charge la base de données Points_Finaux qui sont les points extraits à partir de QGIS, cad les points à conserver pour les calculs finaux, ce sont les arbres situés sur une pente inférieure à 20% et en zone non hydromorphe

library(readr)
Points_finaux <- read_delim("Chunks/Points_finaux.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
View(Points_finaux)
```

#Dernières étapes pour obtenir DataLilou
```{r}
#On se base sur les idTree présents dans "Points_finaux" pour garder que ceux là et y ajouter les infos présentes : pente, zone_defrich, zone_hydro
Points_finaux = Points_finaux %>% mutate(idTree = as.factor(idTree))

#On joint ces informations à Data_VOLUMES et on crée une nouvelle base qui sera notre data finale : DataLilou
DataLilou = inner_join(DataGuyafor_VOLUMES, Points_finaux, keep = FALSE, multiple = "first")

```

#On garde seulement les zones défrichables et les essences commerciales
```{r}
DataLilou <- filter(DataLilou, Zone_defrich == "oui")
DataLilou <- filter(DataLilou, Ess_Com == "Oui")
```


#ENREGISTREMENT DE LA  BASE DE DONNEES DataLilou 
```{r}
save(DataLilou, file = here ("Datas", "DataLilou.RData"))
```

#Verifications 
```{r}
Valeur_unique_id <-- unique(Points_finaux$idTree)
unique(Points_finaux$idTree)
```

