---
title: "DataGuyafor_VOLUMES = Calculs des Volumes sur DataGuyafor_LCY avec le package LoggingLab"
author: "Lilou Kieffer"
date: "2023-05-10"
output: html_document
---

#Construction de la bdd DataGuyafor_VOLUMES en gardant les arbres avec un diamètre supérieur à 45 cm
```{r}
#chargement du package LoggingLab 
library(LoggingLab)

#Welcome to the LoggingLab package
# ?LoggingLab
# ?selected
# ?addtreedim

#chargement de "DataGuyafor_LCY" = la bdd gapfillée et derniers recensements par parcelles 

library(here)
load(here("Datas", "DataGuyafor_LCY.RData"))

#chargement de l'aide de la fonction addtreedim
?addtreedim

#chargement des packages
library(tidyverse)
library(dplyr)
library(tidyr)

#création de la nouvelle table 
DataGuyafor_VOLUMES <- as.tibble(DataGuyafor_VOLUMES)

#colonne DBH
if (!("DBH" %in% names(DataGuyafor_LCY))) {
   tibble::add_column(DataGuyafor_LCY, DBH = NA) #if DBH doesn't exist create it
   DataGuyafor_LCY$DBH = DataGuyafor_LCY$CircCorr/pi
}

DataGuyafor_LCY_filtered <- dplyr::filter(DataGuyafor_LCY, DBH >= 55)

#arguments de la fonction
DataGuyafor_VOLUMES = addtreedim(
  inventory = DataGuyafor_LCY_filtered,
  volumeparameters = ForestZoneVolumeParametersTable,
  crowndiameterparameters = ParamCrownDiameterAllometry,
  advancedloggingparameters = loggingparameters()
)

#Volume de grume
#TreeHarvestableVolume (en m3)

#Poids sur pieds
#AGB (en t)

#Volume de bois sur pieds
#TreeHarvestableVolume_all : AGB / Wooddensity 
DataGuyafor_VOLUMES = DataGuyafor_VOLUMES %>% mutate (TreeHarvestableVolume_all = AGB / WoodDensity)

#Poids de grume
#AGB_grume : TreeHarvestableVolume x Density (t)
DataGuyafor_VOLUMES = DataGuyafor_VOLUMES %>% mutate(AGB_grume = TreeHarvestableVolume*WoodDensity)


#Création d'une colonne qui va nous donner les volumes de bois en m3 par hectare sur pieds en ha pour tous les arbres
DataGuyafor_VOLUMES = DataGuyafor_VOLUMES %>% mutate(TreeHarvestableVolume_all_ha = TreeHarvestableVolume_all /PlotArea)


#On crée une colonne qui va nous donner les volumes en ha pour tous les arbres de la bdd, en prenant chaque Idtree, le nom de sa parcelle, et la PlotArea qui lui correspond !
DataGuyafor_VOLUMES = DataGuyafor_VOLUMES %>% mutate(TreeHarvestableVolume_ha = TreeHarvestableVolume / PlotArea)

#On ajoute la colonne PlotArea_defrich
DataGuyafor_VOLUMES <- left_join(DataGuyafor_VOLUMES, Surface_defrichable, by = "ForestPlot")


#On crée une colonne pour avoir les volumes par hectare de parcelle défrichable seulement
DataGuyafor_VOLUMES = DataGuyafor_VOLUMES %>% mutate(TreeHarvestableVolume_defrich_ha = TreeHarvestableVolume / PlotArea_bis)

# Filtrer les données en excluant les "Paracou_17(Arbocel)" car on ne veut pas étudier les volumes sur cette parcelle

DataGuyafor_VOLUMES <- DataGuyafor_VOLUMES %>%
  filter(ForestPlot != "Paracou_17(Arbocel)" & ForestPlot != "BAFOG_VI" & ForestPlot != "BAFOG_VII")

#
DataGuyafor_VOLUMES <- DataGuyafor_VOLUMES %>%
  mutate(Ess_Com = ifelse(Nom_Scientifique %in% Classi_Ess_Com_Finale$Nom_Scientifique, "Oui", "Non"))%>%
left_join(Classi_Ess_Com_Finale %>% select(Nom_Scientifique, Classe_Emploi, Classe_commerciale, Classe_resistance_meca, Densite, Bois_ronds, Dureté, DME), by = "Nom_Scientifique")

#enregistrement de la base de données "final" avec les "volumes"
save(DataGuyafor_VOLUMES, file = here("Datas", "DataGuyafor_VOLUMES.RData"))

```


#VERSION AVEC LE DBH à 5 CM DE DIAMETRE DANS LE CADRE D'UNE DEFRICHE TOTALE ON GARDE TOUS LES ARBRES 
```{r}
#chargement du package LoggingLab 
library(LoggingLab)

#Welcome to the LoggingLab package
# ?LoggingLab
# ?selected
# ?addtreedim

#chargement de "DataGuyafor_LCY" = la bdd gapfillée et derniers recensements par parcelles 

library(here)
load(here("Datas", "DataGuyafor_LCY.RData"))

#chargement de l'aide de la fonction addtreedim
?addtreedim

#chargement des packages
library(tidyverse)
library(dplyr)
library(tidyr)

#création de la nouvelle table 
DataGuyafor_VOLUMES_total <- as.tibble(DataGuyafor_VOLUMES_total)

#colonne DBH
if (!("DBH" %in% names(DataGuyafor_LCY))) {
   tibble::add_column(DataGuyafor_LCY, DBH = NA) #if DBH doesn't exist create it
   DataGuyafor_LCY$DBH = DataGuyafor_LCY$CircCorr/pi
}

DataGuyafor_LCY_filtered1 <- dplyr::filter(DataGuyafor_LCY, DBH >= 10)

#arguments de la fonction
DataGuyafor_VOLUMES_total = addtreedim(
  inventory = DataGuyafor_LCY_filtered1,
  volumeparameters = ForestZoneVolumeParametersTable,
  crowndiameterparameters = ParamCrownDiameterAllometry,
  advancedloggingparameters = loggingparameters()
)


#Volume de bois sur pieds
#TreeHarvestableVolume_all : AGB / Wooddensity 
DataGuyafor_VOLUMES_total = DataGuyafor_VOLUMES_total %>% mutate (TreeHarvestableVolume_all = AGB / WoodDensity)

#Poids de grume
#AGB_grume : TreeHarvestableVolume x Density (t)
DataGuyafor_VOLUMES_total = DataGuyafor_VOLUMES_total %>% mutate(AGB_grume = TreeHarvestableVolume*WoodDensity)


#Création d'une colonne qui va nous donner les volumes de bois en m3 par hectare sur pieds en ha pour tous les arbres
DataGuyafor_VOLUMES_total = DataGuyafor_VOLUMES_total %>% mutate(TreeHarvestableVolume_all_ha = TreeHarvestableVolume_all /PlotArea) 

#On crée une colonne qui va nous donner les volumes de grume en ha pour tous les arbres de la bdd, en prenant chaque Idtree, le nom de sa parcelle, et la PlotArea qui lui correspond !
DataGuyafor_VOLUMES_total = DataGuyafor_VOLUMES_total %>% mutate(TreeHarvestableVolume_ha = TreeHarvestableVolume / PlotArea)

#On ajoute la colonne PlotArea_defrich
DataGuyafor_VOLUMES_total <- left_join(DataGuyafor_VOLUMES_total, Surface_defrichable, by = "ForestPlot")


#On crée une colonne pour avoir les volumes par hectare de parcelle défrichable seulement
DataGuyafor_VOLUMES_total = DataGuyafor_VOLUMES_total %>% mutate(TreeHarvestableVolume_defrich_ha = TreeHarvestableVolume / PlotArea_bis)

# Filtrer les données en excluant les "Paracou_17(Arbocel)" car on ne veut pas étudier les volumes sur cette parcelle

DataGuyafor_VOLUMES_total <- DataGuyafor_VOLUMES_total %>%
  filter(ForestPlot != "Paracou_17(Arbocel)" & ForestPlot != "BAFOG_VI" & ForestPlot != "BAFOG_VII")

# Effectuer la jointure et créer la nouvelle variable "Ess_Com"
DataGuyafor_VOLUMES_total <- DataGuyafor_VOLUMES_total %>%
  mutate(Ess_Com = ifelse(Nom_Scientifique %in% Classi_Ess_Com_Finale$Nom_Scientifique, "Oui", "Non"))%>%
left_join(Classi_Ess_Com_Finale %>% select(Nom_Scientifique, Classe_Emploi, Classe_commerciale, Classe_resistance_meca, Densite, Bois_ronds, Dureté, DME), by = "Nom_Scientifique")

#enregistrement de la base de données "final" avec les "volumes"
save(DataGuyafor_VOLUMES_total, file = here("Datas", "DataGuyafor_VOLUMES_total.RData"))
```

